
import tweepy
from config import (
    TWITTER_API_KEY, TWITTER_API_SECRET,
    TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_SECRET
)

# Authenticate
auth = tweepy.OAuth1UserHandler(
    TWITTER_API_KEY, TWITTER_API_SECRET,
    TWITTER_ACCESS_TOKEN, TWITTER_ACCESS_SECRET
)
api = tweepy.API(auth)

# Read content generated by Open WebUI
try:
    with open("generated_tweet.txt", "r", encoding="utf-8") as file:
        tweet_text = file.read().strip()
except FileNotFoundError:
    print("⚠️ generated_tweet.txt not found.")
    exit()

tweet_text = "Hello, this is a test tweet!"
if tweet_text:
    try:
        api.update_status(tweet_text)
        print(f"✅ Tweet posted: {tweet_text}")
    except Exception as e:
        print(f"❌ Error posting tweet: {e}")
else:
    print("⚠️ No text found to tweet.")
